name: Feature Request
description: Suggest a new feature or enhancement for Automaker
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the form below to help us understand your request.

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of Automaker does this feature relate to?
      options:
        - UI/UX (User Interface)
        - Agent/AI
        - Kanban Board
        - Git/Worktree Management
        - Project Management
        - Settings/Configuration
        - Documentation
        - Performance
        - Other
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
      default: 0
    validations:
      required: false

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful.
      placeholder: |
        1. When working on...
        2. As a user who needs to...
        3. In situations where...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups, wireframes, or screenshots to help illustrate your feature request.
      placeholder: Drag and drop images here or paste image URLs

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, references, or examples about the feature request here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have provided a clear description of the problem and proposed solution
          required: true
